### PR TITLE
Url pr

### PR DESCRIPTION
**Pull request by Yann151924**
Closes https://github.com/Mineaurion/Aurionchat/pull/31

Copy and refacto some of @burdoto pr -> https://github.com/Mineaurion/Aurionchat/pull/31, use an enum instead of int in config.

I add some support for nested child, i don't know how many nested we can have but the object give the opportunity to have children and so on.

Untested in minecraft. I'll do some test.

TODO:
- [x] change the config ressource to reflect the "enum way"
- [x] do some testing with aurionchat automessage to see if it's ok (normally no prob)

### CODE REVIEW

**Comment by Yann151924** [comment]
I tested it, it's working like a charm.

Is it ok for you @burdoto ? Or any tought ?

PS: i'll update the config file soon

**Comment by burdoto** [comment]
lg2m 👍

**Comment by burdoto** [comment]
little hint; if this PR desc starts with "Closes #31" then it automatically closes that pr and that issue on merge

**Comment by Yann151924** [comment]
I forgot it :D. By the way thanks for the test you made, it was helpfull.

**Comment by burdoto** [comment]
also dont forget to add a github actions runner with the unit tests 

i was hoping to support a bit more by creating the mockup objects ^^ glad ur enjoying it

**Comment by Yann151924** [comment]
The test are added in the ci since gradle will launch it before compiling "common" project.
In more recent project (personal project) i wrote unit test (and more) to cover all the stuff but since the early stage of this plugin i didn't write any and it's a little painfull now to add it

**Pull request merged**
