### PR TITLE
Improve API abstraction for third-party services

### LINKED ISSUE #39: Extracting the structural API of data handled by AurionChat
Hi there;

First of all dont feel bad by the amount of issues and PRs that I open; take your time!
Since I already created the [Discord Link Bot for AurionChat](https://github.com/Mineaurion/Aurionchat/pull/36), in which I had to hand-write code for compatibility to AurionChat; and also am working on [another Project that would implement remote transfer of Minecraft-related data](https://github.com/comroid-git/mc-server-hub), I would like to create a specialized API package for handling such data transfer with (not only) RabbitMQ transfer in mind.

My project not only transfers chat data, but also other [player events](https://github.com/comroid-git/mc-server-hub/blob/main/src/api/main/java/org/comroid/mcsd/api/dto/PlayerEvent.java), such as join/leave as well as death messages (with upcoming custom death message support), and possibly also other related information.

I think both this and my other project would both profit of such a library and a standardized way of communicating and transferring data with each other.

### PR DESCRIPTION
**Pull request by burdoto**
Closes #39

This PR works on the API library in order to make it more abstract for third-party services.

### CODE REVIEW

**Comment by Yann151924** [comment]
I want to push some stuff into the branch but i think i don't have all the right needed. Can you check out on your end ?
I can get the branch in the repo but we will lost some stuff (pr request & stuff like this) if i did this.

Edit: i push the branch on the repo, just to backup my work for now

**Comment by burdoto** [comment]
hm, i have all my PRs set to allow edits from maintainers; so i'm not sure what the issue is either. are you pushing to the source branch, or to the internal branch of the PR?

i saw your change that you are removing lombok alongside with other dependencies; however removing lombok does not give much profit in terms of library size and usage; it is only present during compilation; and adds to code readability.

i would prefer to find a better way of communicating than through gh issue comments; would you be happy joining my [discord server](https://discord.gg/yWfE3WB5)?

**Comment by Yann151924** [comment]
I'm pushing to your remote normally it's this way but it's not working.

I'm not a fan of lombok, surely it's add readability but i prefer to have the function directly in the code.

I join the discord :)

**Comment by burdoto** [comment]
i merged your branch into the PR

**Comment by Yann151924** [comment]
#55 will be the correct pull request instead of this one. I will add some stuff in the branch

**Pull request closed without merging**
